FROM registry.ci.openshift.org/ocp/builder:rhel-9-base-openshift-4.19

RUN dnf install -y \
    python3 \
    python3-pip \
    python3-pyyaml \
    jq \
    git \
    && dnf clean all

RUN pip3 install --no-cache-dir \
    ansible-core \
    boto3 \
    kubernetes \
    openshift

RUN curl -sL https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz \
    | tar -xz -C /usr/local/bin oc kubectl

COPY . /rosa-hcp-e2e-test
WORKDIR /rosa-hcp-e2e-test
