- name: Create rosa-creds-secret variables
  no_log: true
  set_fact:
    secret_name: "rosa-creds-secret"
    ocm_client_id: "{{ lookup('env', 'OCM_CLIENT_ID') | default(OCM_CLIENT_ID, true) }}"
    ocm_client_secret: "{{ lookup('env', 'OCM_CLIENT_SECRET') | default(OCM_CLIENT_SECRET, true) }}"
    ocm_client_api_url: "{{ lookup('env', 'OCM_API_URL') | default('https://api.stage.openshift.com', true) }}"

- name: Create or update rosa-creds-secret in {{ capa_namespace }} namespace
  no_log: true
  shell: |
    oc -n {{ capa_namespace }} create secret generic {{ secret_name }} \
      --from-literal=ocmClientID={{ ocm_client_id | quote }} \
      --from-literal=ocmClientSecret={{ ocm_client_secret | quote }} \
      --from-literal=ocmApiUrl={{ ocm_client_api_url | quote }} \
      --dry-run=client -o yaml | oc apply -f -

- name: Create or update rosa-creds-secret in target namespace
  no_log: true
  shell: |
    oc -n {{ rosa_hcp_namespace | default('ns-rosa-hcp') }} create secret generic {{ secret_name }} \
      --from-literal=ocmClientID={{ ocm_client_id | quote }} \
      --from-literal=ocmClientSecret={{ ocm_client_secret | quote }} \
      --from-literal=ocmApiUrl={{ ocm_client_api_url | quote }} \
      --dry-run=client -o yaml | oc apply -f -
  when: rosa_hcp_namespace is defined and rosa_hcp_namespace != capa_namespace

- name: Confirm rosa-creds-secret created
  debug:
    msg: "rosa-creds-secret created successfully"
