- name: Create rosa-creds-secret variables
  no_log: true
  set_fact:
    secret_name: "rosa-creds-secret"
    ocm_client_id: "{{ OCM_CLIENT_ID }}"
    ocm_client_secret: "{{ OCM_CLIENT_SECRET }}"
    ocm_client_api_url: "https://api.stage.openshift.com"

- name: Create or update rosa-creds-secret in {{ capa_namespace }} namespace
  no_log: true
  shell: |
    oc -n {{ capa_namespace }} create secret generic {{ secret_name }} \
      --from-literal=ocmClientID={{ ocm_client_id }} \
      --from-literal=ocmClientSecret={{ ocm_client_secret }} \
      --from-literal=ocmApiUrl={{ ocm_client_api_url }} \
      --dry-run=client -o yaml | oc apply -f -

- name: Create or update rosa-creds-secret in target namespace
  no_log: true
  shell: |
    oc -n {{ rosa_hcp_namespace | default('ns-rosa-hcp') }} create secret generic {{ secret_name }} \
      --from-literal=ocmClientID={{ ocm_client_id }} \
      --from-literal=ocmClientSecret={{ ocm_client_secret }} \
      --from-literal=ocmApiUrl={{ ocm_client_api_url }} \
      --dry-run=client -o yaml | oc apply -f -
  when: rosa_hcp_namespace is defined and rosa_hcp_namespace != capa_namespace

- name: Confirm rosa-creds-secret created
  debug:
    msg: "rosa-creds-secret created successfully"
