---
- block:
    - debug:
        msg: "FAIL: {{ feature_id }} was requested but {{ fail_detail }}"
    - set_fact:
        features_failed: "{{ features_failed | int + 1 }}"
  when: "feature_id in requested_features_list"

- block:
    - debug:
        msg: "SKIP: {{ feature_id }} not requested"
    - set_fact:
        features_skipped: "{{ features_skipped | int + 1 }}"
  when: "feature_id not in requested_features_list"
