- name: Verify the MCE CAPI/CAPA environment is congifured properly
  hosts: localhost
  any_errors_fatal: true
  vars_files:
    - ../vars/vars.yml
  tasks:
    - name: Load user variables
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - files:
            - ../vars/user_vars.yml
          skip: true

    - name: Set cluster credentials
      set_fact:
        ocp_user: "{{ lookup('env', 'OCP_HUB_CLUSTER_USER') | default(OCP_HUB_CLUSTER_USER, true) }}"
        ocp_password: "{{ lookup('env', 'OCP_HUB_CLUSTER_PASSWORD') | default(OCP_HUB_CLUSTER_PASSWORD, true) }}"
        api_url: "{{ lookup('env', 'OCP_HUB_API_URL') | default(OCP_HUB_API_URL, true) }}"
        mce_namespace: "{{ lookup('env', 'MCE_NAMESPACE') | default(MCE_NAMESPACE, true) }}"

    - name: Prepare ansible runner host
      include_tasks: ../tasks/prepare_ansible_runner.yml
      when: not skip_ansible_runner | bool

    - name: Login OCP
      include_tasks: ../tasks/login_ocp.yml

    - name: Verify capi/capa environment configured properly
      include_tasks: ../tasks/validate-capa-environment.yml
