apiVersion: v1
kind: Service
metadata:
  name: agent-v2
  namespace: rosa-hcp-agent
  labels:
    app: agent-v2
spec:
  type: ClusterIP
  selector:
    app: agent-v2
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
